export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// eslint-disable-next-line react/prop-types
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
